# .swiftlint.yml

included:
  - Salah
  - SalahTests

disabled_rules:
  - line_length
  - control_statement

function_body_length:
  warning: 200

file_length:
  warning: 1200

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 1000

type_body_length:
  warning: 400
  
large_tuple:
  warning: 8
